# Generated by Django 3.0.2 on 2020-10-14 13:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Texto')),
                ('image', models.ImageField(upload_to=core.models.highlight_directory_path, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Destaque',
                'verbose_name_plural': 'Destaques',
            },
        ),
    ]
