# Generated by Django 3.2.7 on 2024-06-12 22:50

import core.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True, verbose_name='Título')),
                ('description', models.CharField(max_length=60, null=True, verbose_name='Descrição Rápida')),
                ('image', models.ImageField(upload_to=core.models.carousel_image_directory_path, verbose_name='Imagem')),
                ('list_order', models.IntegerField(null=True, unique=True, verbose_name='Ordem no Carrossel')),
            ],
            options={
                'verbose_name': 'Imagem do Carrossel',
                'verbose_name_plural': 'Imagens do Carrossel',
                'ordering': ['list_order'],
            },
        ),
        migrations.CreateModel(
            name='Colaborators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, default=0, help_text='Insira o ano de início do projeto', verbose_name='Ano de início do projeto')),
                ('name_project', models.CharField(blank=True, help_text='Insira o nome do projeto', max_length=200, verbose_name='Nome do projeto')),
                ('student_name', models.CharField(blank=True, help_text='Ins        ira o nome do(s) bolsista(s) do projeto', max_length=300, verbose_name='Nome do(s) bolsista(s)')),
                ('advisor_name', models.CharField(blank=True, help_text='Insira o nome do(s) orientador(es) do projeto', max_length=200, verbose_name='Nome do(s) orientador(es)')),
                ('co_advisor_name', models.CharField(blank=True, help_text='Insira o nome do(s) coorientador(es) do projeto', max_length=400, verbose_name='Nome do(s) coorientador(es)')),
            ],
            options={
                'verbose_name': 'Colaboradores',
                'verbose_name_plural': 'Colaboradores do projeto',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Identificador')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Texto')),
                ('image', models.ImageField(upload_to=core.models.highlight_directory_path, verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('more_information', models.TextField(null=True, verbose_name='Mais Informações')),
            ],
            options={
                'verbose_name': 'Destaque',
                'verbose_name_plural': 'Destaques',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', tinymce.models.HTMLField(verbose_name='Conteúdo')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Postado em')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='PhotoPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to=core.models.publication_directory_path, verbose_name='Imagens')),
                ('small_image', models.ImageField(editable=False, max_length=500, null=True, upload_to=core.models.small_publication_directory_path)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.publication', verbose_name='Publicação')),
            ],
            options={
                'verbose_name': 'Foto da publicação',
                'verbose_name_plural': 'Fotos das plublicações',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Nome')),
                ('link', models.URLField(max_length=400, verbose_name='Link')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content', verbose_name='Cultura')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
