# Generated by Django 3.0.2 on 2020-10-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='description',
            field=models.CharField(max_length=60, null=True, verbose_name='Descrição Rápida'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(max_length=25, null=True, verbose_name='Título'),
        ),
    ]
