# Generated by Django 3.0.2 on 2020-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201026_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['title'], 'verbose_name': 'Imagem do Carrossel', 'verbose_name_plural': 'Imagens do Carrossel'},
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='list_order',
            field=models.IntegerField(null=True, verbose_name='Ordem no Carrossel'),
        ),
    ]
