# Generated by Django 3.0.2 on 2020-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201026_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='list_order',
            field=models.IntegerField(null=True, unique=True, verbose_name='Ordem no Carrossel'),
        ),
    ]
