# Generated by Django 3.0.2 on 2020-10-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201026_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['list_order'], 'verbose_name': 'Imagem do Carrossel', 'verbose_name_plural': 'Imagens do Carrossel'},
        ),
    ]
