# Generated by Django 3.1.3 on 2021-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210114_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
