# Generated by Django 3.1.3 on 2021-01-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210115_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='more_information',
            field=models.TextField(null=True, verbose_name='Mais Informações'),
        ),
    ]
