# Generated by Django 3.2.7 on 2024-05-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(max_length=13, verbose_name='Número do sistema que enviou a mensagem')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='Nome de quem recebeu a mensagem')),
                ('receiver_number', models.CharField(max_length=13, verbose_name='Número de quem recebeu a mensagem')),
                ('timestamp', models.IntegerField(verbose_name='Timestamp (Data)')),
                ('message_text', models.TextField(verbose_name='Texto da mensagem')),
                ('message_id', models.CharField(default='', max_length=200, verbose_name='Id da mensagem')),
                ('status_log', models.TextField(default='', verbose_name='Atualização dos status desta mensagem')),
            ],
        ),
    ]
