# Generated by Django 3.2.25 on 2025-12-11 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='ID do Chat no Telegram')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username do Telegram')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Primeiro Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de inscrição')),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True, verbose_name='Último alerta enviado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Inscrição do Telegram',
                'verbose_name_plural': 'Inscrições do Telegram',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('telegram_first_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_confirmation', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Confirmação de Mensagem',
                'verbose_name_plural': 'Confirmações de Mensagem',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('alert', 'Alerta'), ('confirmation', 'Confirmação'), ('notification', 'Notificação')], default='notification', max_length=20, verbose_name='Tipo de Mensagem')),
                ('math_model_reference', models.CharField(blank=True, max_length=100, verbose_name='Referência do Modelo')),
                ('message_text', models.TextField(verbose_name='Texto da mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falha')], default='pending', max_length=20, verbose_name='Status')),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='ID externo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_log', models.JSONField(default=list, verbose_name='Histórico de status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('delivery_details', models.JSONField(default=dict, verbose_name='Detalhes da entrega')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disease.disease', verbose_name='Doença relacionada')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='accounts.profile', verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status'], name='whatsapp_me_status_375b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='whatsapp_me_created_d0484f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='whatsapp_me_message_263bdd_idx'),
        ),
    ]
