# Generated by Django 3.1.3 on 2021-02-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('institution', models.CharField(max_length=150, verbose_name='Instituição onde trabalha/estuda')),
                ('role', models.CharField(help_text='Utilize como base seu cargo na instituição citada acima.', max_length=100, verbose_name='Cargo de ofício')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
