# Generated by Django 3.2.25 on 2025-12-11 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data de envio')),
                ('status', models.CharField(choices=[('sent', 'Em análise'), ('accepted', 'Aceita'), ('denied', 'Negada')], default='sent', max_length=8)),
                ('term', models.BooleanField(default=False, verbose_name='Termo de cessão de uso de materiais audiovisuais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('institution', models.CharField(max_length=150, verbose_name='Instituição')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Telefone')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='Receber alertas por WhatsApp')),
                ('whatsapp_verified', models.BooleanField(default=False, verbose_name='WhatsApp Verificado')),
                ('whatsapp_opt_in', models.BooleanField(default=False, verbose_name='Receber Alertas no WhatsApp')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=10, verbose_name='RG')),
                ('get_messages', models.BooleanField(default=False)),
                ('alerts_for_diseases', models.ManyToManyField(blank=True, to='disease.Disease', verbose_name='Doenças para alerta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Contribuition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuitions', to='accounts.profile', verbose_name='Perfil')),
            ],
        ),
    ]
