# Generated by Django 3.1.3 on 2021-03-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(max_length=150, verbose_name='Instituição de trabalho e/ou estudo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telefone fixo ou celular'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(help_text='Utilize como base seu cargo na instituição citada.', max_length=100, verbose_name='Cargo de ofício'),
        ),
    ]
