# Generated by Django 3.2.25 on 2026-08-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0002_seed_regions'),
        ('accounts', '0003_unique_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert_regions',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='herbarium.Region', verbose_name='Regiões de interesse para alertas'),
        ),
    ]
