# Generated by Django 3.2.25 on 2026-08-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_alert_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Seu @ no Telegram, sem o @. Opcional — necessário apenas para receber os alertas pelo bot.', max_length=32, null=True, unique=True, verbose_name='Usuário do Telegram'),
        ),
    ]
