# Generated by Django 3.2.25 on 2026-09-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_backfill_telegram_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alert_regions',
        ),
    ]
