"""
Django settings for herbario project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "eg%2hr5a4y@6w+*kipd5by()+vwqkaqqf_s4gj9h%!g_a(l!t6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["labfito.vacaria.ifrs.edu.br", "localhost"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "tinymce",
    "django_extensions",
    "crispy_forms",
    'crispy_bootstrap4',
    "core",
    'accounts.apps.AccountsConfig',
    'alerts.apps.AlertsConfig',
    "background_task",
    "herbarium",
    "disease",
    "whatsapp_messages",
    "telegram_bot.apps.TelegramBotConfig",
    "celery",
    # dashboard deve ficar por ultimo na lista
    "dashboard",
]

# CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'

CRISPY_TEMPLATE_PACK = "bootstrap4"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# Será sobreescrito no local_settings.py
DATABASES = {}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

#CRONJOBS = [
#    ('*/5 * * * *', 'alerts.management.commands.process_alertas.Command'),
#    ('0 * * * *', 'alerts.management.commands.cleanup_old_data.Command'),
#]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
# STATICFILES_DIRS = (os.path.join(BASE_DIR, 'config/core/static'),)

# Arquivos de mídia

# MEDIA_ROOT = os.path.join(BASE_DIR, "herbario", "media")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MEDIA_URL = "/media/"

# Imagens recebidas pelo bot do Telegram para o modelo de IA, separadas por uso
# em training/ e test/. Ficam fora do MEDIA_ROOT porque não são servidas pelo
# site: o banco guarda só o caminho relativo a esta pasta. Ver telegram_bot/storage.py
AI_MEDIA_ROOT = os.path.join(BASE_DIR, "media-ia")

# Sem isto o Django usa o padrão "/accounts/login/", que dá 404: config/urls.py
# não inclui accounts.urls (esse app é código morto). O efeito era todo
# @login_required / LoginRequiredMixin mandar o visitante para uma página
# inexistente em vez da tela de login.
LOGIN_URL = "/painel/login/"

LOGIN_REDIRECT_URL = "/painel/"

LOGOUT_REDIRECT_URL = "/painel/login/"

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


# Usado nas mensagens do bot para apontar o usuário ao cadastro do sistema.
SITE_URL = os.getenv('SITE_URL', 'https://labfito.vacaria.ifrs.edu.br')

# Bot do Telegram. Cada ambiente usa o seu, definido no .env:
#   produção -> labfito_vacaria_bot (padrão abaixo)
#   local    -> labfito_teste_bot
# O token NUNCA vai no código: o repositório é público. Sem TELEGRAM_BOT_TOKEN
# no ambiente, o bot não sobe e nenhuma mensagem é enviada.
TELEGRAM_BOT_USERNAME = os.getenv('TELEGRAM_BOT_USERNAME', 'labfito_vacaria_bot')

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')

TELEGRAM_API_URL = "https://api.telegram.org/bot"

# Sobrescrito no local_settings.py
TELEGRAM_SECRET_TOKEN = os.getenv('TELEGRAM_SECRET_TOKEN', "")

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    # WARNING, e não DEBUG: em DEBUG o Django registra até as variáveis de
    # template que não resolvem, e em produção o arquivo chegou a 12 GB num disco
    # de 28 GB (07/10/2026). Erros 500 continuam saindo com o traceback completo.
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': '/var/log/django/debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

from .local_settings import *

TESTING = False

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Sao_Paulo'