# Generated by Django 2.2.2 on 2019-06-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Imagem'),
        ),
    ]
