# Generated by Django 2.2.2 on 2019-06-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0003_auto_20190628_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='family',
            field=models.CharField(blank=True, choices=[('ss', 'dddsd')], max_length=100, verbose_name='Família'),
        ),
    ]
