# Generated by Django 2.2.2 on 2019-07-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0004_auto_20190628_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='family',
            field=models.CharField(blank=True, max_length=100, verbose_name='Família'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_class',
            field=models.CharField(blank=True, choices=[('Gramosa', 'gramosa'), ('Abacaxium', 'abacaxium'), ('matinhum', 'matinhum')], max_length=100, verbose_name='Classe'),
        ),
    ]
