# Generated by Django 2.2.2 on 2019-08-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0006_auto_20190813_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='images',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
