# Generated by Django 2.2.2 on 2019-08-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0009_auto_20190814_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='imagess'),
        ),
    ]
