# Generated by Django 2.2.2 on 2019-08-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0012_auto_20190814_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/ None'),
        ),
    ]
