# Generated by Django 2.2.2 on 2019-08-16 11:19

from django.db import migrations, models
import herbario.herbarium.models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0014_auto_20190814_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=herbario.herbarium.models.plant_directory_path),
        ),
    ]
