# Generated by Django 2.2.2 on 2019-09-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0016_auto_20190912_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
    ]
