# Generated by Django 2.2.2 on 2019-10-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0018_auto_20191016_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='division',
        ),
        migrations.AlterField(
            model_name='plant',
            name='family',
            field=models.CharField(blank=True, choices=[('Dicotiledôneas', (('amaranthaceae', 'Amaranthaceae'), ('asteraceae', 'Asteraceae'), ('brassicaceae', 'Brassicaceae'), ('caryophyllaceae', 'Caryophyllaceae'), ('cyperaceae', 'Cyperaceae'), ('convolvulaceae', 'Convolvulaceae'), ('euphobiaceae', 'Euphobiaceae'), ('malvaceae', 'Malvaceae'))), ('Monocotiledôneas', (('plantaginaceae', 'Plantaginaceae'), ('poaceae', 'Poaceae'), ('polygonaceae', 'Polygonaceae'), ('rubiaceae', 'Rubiaceae'), ('sapindaceae', 'Sapindaceae'), ('solanaceae', 'Solanaceae')))], max_length=100, verbose_name='Família'),
        ),
    ]
