# Generated by Django 2.2.2 on 2019-10-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0019_auto_20191016_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='division',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Divisão'),
        ),
    ]
