# Generated by Django 3.2.25 on 2025-10-29 19:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '00001_initial'),
        ('disease', '00001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do modelo matemático')),
                ('source_code', models.TextField(max_length=1000)),
                ('alert_threshold', models.FloatField(blank=True, null=True, verbose_name='Limite para alertas')),
                ('alert_message', models.TextField(blank=True, verbose_name='Mensagem de alerta')),
                ('evaluation_period', models.PositiveIntegerField(default=6, verbose_name='Período de avaliação (horas)')),
                ('require_continuous_reports', models.BooleanField(default=True, verbose_name='Requisito de relatórios contínuos')),
                ('min_positive_reports', models.PositiveIntegerField(default=3, verbose_name='Mínimo de relatórios positivos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('min_conditions_hours', models.PositiveIntegerField(default=6, verbose_name='Horas mínimas de condições favoráveis')),
                ('require_minimum_hours', models.BooleanField(default=False, verbose_name='Exigir horas mínimas')),
                ('accumulation_start_hours', models.PositiveIntegerField(default=0, verbose_name='Horas para iniciar acumulação')),
                ('retrospective_analysis_hours', models.PositiveIntegerField(default=6, verbose_name='Horas para análise retrospectiva')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disease.disease', verbose_name='Doença')),
            ],
            options={
                'verbose_name': 'Modelo matemático',
                'verbose_name_plural': 'Modelos matemáticos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo para identificar o requisito', max_length=200, verbose_name='Nome do requisito')),
                ('parameter', models.CharField(choices=[('temperature', 'Temperatura'), ('humidity', 'Umidade'), ('custom', 'Personalizado')], help_text='Parâmetro meteorológico a ser verificado', max_length=20, verbose_name='Parâmetro')),
                ('operator', models.CharField(choices=[('>', 'Maior que'), ('<', 'Menor que'), ('>=', 'Maior ou igual'), ('<=', 'Menor ou igual'), ('==', 'Igual a'), ('!=', 'Diferente de')], help_text='Operador de comparação', max_length=3, verbose_name='Operador')),
                ('value', models.FloatField(help_text='Valor limite para comparação', verbose_name='Valor de referência')),
                ('duration_hours', models.FloatField(blank=True, help_text='Tempo mínimo que a condição deve ser mantida (opcional)', null=True, verbose_name='Duração mínima (horas)')),
                ('custom_expression', models.TextField(blank=True, help_text='Expressão customizada usando variáveis: t, rh, rain', verbose_name='Expressão personalizada')),
                ('is_active', models.BooleanField(default=True, help_text='Se desmarcado, este requisito será ignorado', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20, verbose_name='Identificador da estação')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('lat_coordinate', models.FloatField(null=True, verbose_name='Latitude')),
                ('lon_coordinate', models.FloatField(null=True, verbose_name='Longitude')),
                ('description', models.TextField(help_text='Endereço, ponto de referência, responsável...', max_length=400, null=True, verbose_name='Descrição da estação')),
            ],
            options={
                'verbose_name': 'Estação',
                'verbose_name_plural': 'Estações',
            },
        ),
        migrations.CreateModel(
            name='TypeSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('metric', models.CharField(choices=[('mm', 'Milímetros'), ('C', 'Graus ºC'), ('CS', 'Graus ºC Solo'), ('human', 'Sensor Humano'), ('bool', 'Booleano'), ('ur', 'Umidade Relativa %'), ('%', 'Umidade % (depreciado)'), ('wm2', 'Wm2'), ('K', 'Graus ºK'), ('m/s', 'm/s (depreciado)'), ('m_s', 'm/s'), ('mbar', 'Milibares'), ('v', 'Volts'), ('pct', 'Porcentagem'), ('int', 'Inteiro')], max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de Sensor',
                'verbose_name_plural': 'Tipos de Sensores',
            },
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.disease', verbose_name='Doença')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alerts.station', verbose_name='Estação')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.typesensor', verbose_name='Tipo do sensor')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('umidade', models.FloatField(blank=True, null=True)),
                ('tempo_chuva', models.FloatField(blank=True, null=True)),
                ('risk_alert', models.BooleanField(default=False)),
                ('reading_temp', models.FloatField(blank=True, null=True, verbose_name='Leitura Temperatura')),
                ('reading_humidity', models.FloatField(blank=True, null=True, verbose_name='Leitura Umidade')),
                ('reading_rain', models.FloatField(blank=True, null=True, verbose_name='Leitura Chuva')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('processing', models.BooleanField(default=False, verbose_name='Em processamento')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.station')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True, verbose_name='Valor')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='alerts.report', verbose_name='Relatório')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.sensor', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='MathModelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('accumulated_value', models.FloatField(default=0.0, help_text='Soma acumulada dos valores até atingir o threshold', verbose_name='Valor Acumulado')),
                ('is_alert_triggered', models.BooleanField(default=False, help_text='Indica se este resultado disparou um alerta', verbose_name='Alerta disparado')),
                ('mathmodel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.mathmodel', verbose_name='Modelo matemático')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alerts.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Resultado de modelo matemático',
                'verbose_name_plural': 'Resultados dos modelos matemáticos',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MathModelRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='Se desmarcado, este requisito é opcional', verbose_name='Obrigatório')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de verificação dos requisitos', verbose_name='Ordem')),
                ('math_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mathmodel_requirements', to='alerts.mathmodel')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_mathmodels', to='alerts.requirement')),
            ],
            options={
                'verbose_name': 'Requisito do Modelo',
                'verbose_name_plural': 'Requisitos dos Modelos',
                'ordering': ['order'],
                'unique_together': {('math_model', 'requirement')},
            },
        ),
        migrations.AddField(
            model_name='mathmodel',
            name='requirements',
            field=models.ManyToManyField(blank=True, through='alerts.MathModelRequirement', to='alerts.Requirement', verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='mathmodel',
            name='stations',
            field=models.ManyToManyField(blank=True, to='alerts.Station', verbose_name='Estações associadas'),
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('description', models.TextField(blank=True, help_text='Descrição da constante', verbose_name='Descrição')),
                ('mathmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alerts.mathmodel')),
            ],
            options={
                'verbose_name': 'Constante',
                'verbose_name_plural': 'Constantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(verbose_name='Detalhes')),
                ('calculated_value', models.FloatField(verbose_name='Valor Calculado')),
                ('alert_message', models.TextField(blank=True, verbose_name='Mensagem de Alerta')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('math_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.mathmodel', verbose_name='Modelo Matemático')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Histórico de Alerta',
                'verbose_name_plural': 'Históricos de Alertas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorInMathModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divider', models.BooleanField(default=False, help_text='Marcar se este sensor deve ser usado como divisor no gráfico', verbose_name='Usar como divisor')),
                ('in_graph', models.BooleanField(default=True, help_text='Marcar se este sensor deve ser exibido no gráfico principal', verbose_name='Mostrar no gráfico')),
                ('mean', models.BooleanField(default=False)),
                ('mathmodel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.mathmodel', verbose_name='Modelo matemático')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.sensor', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': 'Sensor no modelo matemático',
                'verbose_name_plural': 'Sensores nos modelos matemáticos',
                'unique_together': {('mathmodel', 'sensor')},
            },
        ),
        migrations.CreateModel(
            name='HourlyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.DateTimeField(verbose_name='Início da hora')),
                ('hour_end', models.DateTimeField(verbose_name='Fim da hora')),
                ('value', models.FloatField(default=0.0, verbose_name='Valor calculado')),
                ('accumulated_value', models.FloatField(default=0.0, verbose_name='Valor acumulado')),
                ('requirements_met', models.BooleanField(default=False, verbose_name='Requisitos atendidos')),
                ('math_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.mathmodel')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.station')),
            ],
            options={
                'verbose_name': 'Resultado Horário',
                'verbose_name_plural': 'Resultados Horários',
                'unique_together': {('math_model', 'station', 'hour_start')},
            },
        ),
        migrations.CreateModel(
            name='ConditionWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulation_start', models.DateTimeField(null=True, verbose_name='Início da acumulação')),
                ('last_valid_report', models.DateTimeField(null=True, verbose_name='Último relatório válido')),
                ('expected_alert_time', models.DateTimeField(null=True, verbose_name='Horário esperado do alerta')),
                ('current_accumulated_value', models.FloatField(default=0.0, verbose_name='Valor acumulado atual')),
                ('is_accumulation_active', models.BooleanField(default=False, verbose_name='Acumulação ativa')),
                ('math_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.mathmodel')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.station')),
            ],
            options={
                'unique_together': {('math_model', 'station')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(verbose_name='Início da janela')),
                ('window_end', models.DateTimeField(verbose_name='Fim da janela')),
                ('reports_in_window', models.PositiveIntegerField(default=0, verbose_name='Relatórios na janela')),
                ('valid_reports', models.PositiveIntegerField(default=0, verbose_name='Relatórios válidos')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Janela completa')),
                ('accumulated_value', models.FloatField(default=0.0, verbose_name='Valor acumulado')),
                ('math_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.mathmodel', verbose_name='Modelo matemático')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Janela de Análise',
                'verbose_name_plural': 'Janelas de Análise',
                'unique_together': {('math_model', 'station', 'window_start')},
            },
        ),
    ]
