# Generated by Django 3.2.25 on 2026-08-11 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0002_seed_regions'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='herbarium.region', verbose_name='Região'),
        ),
    ]
