# Generated by Django 3.2.7 on 2024-06-12 23:48

from django.db import migrations


def convert_char_to_float(apps, schema_editor):
    Report = apps.get_model('alerts', 'Report')
    for report in Report.objects.all():
        try:
            report.value_new = float(report.value)
        except ValueError:
            if report.value.strip().lower() == "nan":
                report.value_new = None
            else:
                raise

        report.save()


class Migration(migrations.Migration):
    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_char_to_float),
    ]
