# Generated by Django 3.2.25 on 2026-09-29 18:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_alert_regions'),
        ('alerts', '0002_station_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex.: Sede da propriedade, Talhão norte...', max_length=100, verbose_name='Nome')),
                ('kind', models.CharField(choices=[('urban_address', 'Endereço urbano'), ('rural_address', 'Endereço rural'), ('coordinates', 'Coordenadas'), ('station', 'Estação')], default='urban_address', max_length=20, verbose_name='Tipo de localização')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('radius_km', models.PositiveSmallIntegerField(default=20, help_text='Estações a até esta distância do ponto também geram alertas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Raio de interesse (km)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_points', to='accounts.profile', verbose_name='Usuário')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_points', to='alerts.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Ponto de interesse',
                'verbose_name_plural': 'Pontos de interesse',
                'ordering': ['name', 'pk'],
            },
        ),
    ]
