# Generated by Django 3.2.7 on 2024-05-13 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_messageconfirmation_verificationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='user',
            new_name='profile',
        ),
    ]
