# Generated by Django 3.2.25 on 2025-11-10 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20251106_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerthistory',
            options={'ordering': ['-alert_time'], 'verbose_name': 'Histórico de Alerta', 'verbose_name_plural': 'Históricos de Alertas'},
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='alert_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Alerta'),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='alert_value',
            field=models.FloatField(default=0.0, verbose_name='Valor do Alerta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='alert_message',
            field=models.TextField(verbose_name='Mensagem de Alerta'),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='calculated_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Calculado'),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='details',
            field=models.TextField(blank=True, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Timestamp'),
        ),
    ]
