# Generated by Django 3.2.7 on 2024-05-13 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0003_rename_user_verificationcode_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='profile',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
