# Generated by Django 3.2.7 on 2024-07-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_requirement_math_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='math_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alerts.mathmodel', verbose_name='Modelo matematico'),
        ),
    ]
