# Generated by Django 3.2.7 on 2024-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20240513_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='user',
        ),
        migrations.DeleteModel(
            name='WhatsappNumber',
        ),
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.CharField(max_length=20, verbose_name='Identificador da estação'),
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
