# Generated by Django 3.2.7 on 2024-07-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_requirement_math_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='used_internally',
            field=models.BooleanField(default=False, verbose_name='Usado internamente'),
        ),
        migrations.AlterField(
            model_name='typesensor',
            name='metric',
            field=models.CharField(choices=[('mm', 'Milímetros'), ('C', 'Graus ºC'), ('CS', 'Graus ºC Solo'), ('human', 'Sensor Humano'), ('bool', 'Booleano'), ('ur', 'Umidade Relativa %'), ('%', 'Umidade % (depreciado)'), ('wm2', 'Wm2'), ('K', 'Graus ºK'), ('m/s', 'm/s (depreciado)'), ('m_s', 'm/s'), ('mbar', 'Milibares'), ('v', 'Volts'), ('pct', 'Porcentagem'), ('int', 'Inteiro')], max_length=10),
        ),
    ]
