# Generated by Django 3.2.7 on 2024-06-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20240603_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='value_new',
            field=models.FloatField(null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='typesensor',
            name='metric',
            field=models.CharField(choices=[('mm', 'Milímetros'), ('C', 'Graus ºC'), ('CS', 'Graus ºC Solo'), ('bool', 'Sensor Humano'), ('ur', 'Umidade Relativa %'), ('%', 'Umidade % (depreciado)'), ('wm2', 'Wm2'), ('K', 'Graus ºK'), ('m/s', 'm/s (depreciado)'), ('m_s', 'm/s'), ('mbar', 'Milibares'), ('v', 'Volts'), ('pct', 'Porcentagem')], max_length=10),
        ),
    ]
