# Generated by Django 3.2.7 on 2024-06-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_20240612_1709'),
    ]

    operations = [
    ]
