# Generated by Django 3.2.7 on 2024-07-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_20240722_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='min_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo mínimo'),
        ),
    ]
