# Generated by Django 3.2.7 on 2024-10-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
        ('alerts', '0014_report_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathmodel',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disease.disease', verbose_name='Doença'),
        ),
    ]
