# Generated by Django 3.2.7 on 2024-10-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_typesensor_metric'),
        ('alerts', '0015_alter_mathmodel_disease'),
    ]

    operations = [
    ]
