# Generated by Django 3.2.7 on 2024-10-18 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0015_alter_mathmodel_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='alerts.report', verbose_name='Relatório'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='report',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alerts.station', verbose_name='Estação'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
