# Generated by Django 3.2.7 on 2024-12-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0018_delete_useralert'),
        ('alerts', '0019_alter_typesensor_metric'),
    ]

    operations = [
    ]
