# Generated by Django 3.2.7 on 2024-12-03 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_alerts_for_diseases'),
        ('disease', '0001_initial'),
        ('alerts', '0020_merge_20241202_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='min_time',
            field=models.FloatField(blank=True, help_text='Tempo mínimo em horas', null=True, verbose_name='Tempo mínimo'),
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.disease', verbose_name='Doença')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
    ]
