# Generated by Django 3.2.7 on 2024-12-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0022_auto_20241203_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathmodel',
            name='stations',
            field=models.ManyToManyField(blank=True, to='alerts.Station', verbose_name='Estaçôes atreladas'),
        ),
    ]
