# Generated by Django 5.2.5 on 2025-09-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0023_alter_mathmodel_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
