# Generated by Django 5.2.5 on 2025-10-01 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0024_alter_reading_time_alter_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data'),
        ),
    ]
