# Generated by Django 3.2.25 on 2025-10-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuário do Telegram',
                'verbose_name_plural': 'Usuários do Telegram',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
