# Generated by Django 3.2.25 on 2026-07-22 02:23

from django.db import migrations, models
import django.db.models.deletion
import telegram_bot.models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', max_length=500, upload_to=telegram_bot.models.telegram_photo_directory_path, verbose_name='Imagem', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_id', models.CharField(blank=True, max_length=200, verbose_name='File ID')),
                ('file_unique_id', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='File Unique ID')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('caption', models.TextField(blank=True, verbose_name='Legenda')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID da mensagem')),
                ('media_group_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID do álbum')),
                ('source', models.CharField(choices=[('photo', 'Foto'), ('document', 'Arquivo')], default='photo', max_length=20, verbose_name='Origem')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebida em')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='telegram_bot.telegramuser', verbose_name='Usuário do Telegram')),
            ],
            options={
                'verbose_name': 'Imagem do Telegram',
                'verbose_name_plural': 'Imagens do Telegram',
                'ordering': ['-received_at'],
            },
        ),
    ]
