# Generated by Django 3.2.25 on 2026-08-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_unique_user_email'),
        ('telegram_bot', '0002_telegramphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='awaiting_email_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aguardando e-mail desde'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='linked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vinculado em'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_user', to='accounts.profile', verbose_name='Conta vinculada'),
        ),
    ]
