# Generated by Django 3.2.25 on 2026-08-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_telegramuser_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='awaiting_email_since',
        ),
    ]
