# Generated by Django 3.2.25 on 2026-09-29 17:24

from django.db import migrations, models
import telegram_bot.models
import telegram_bot.storage


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_remove_telegramuser_awaiting_email_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramphoto',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Uso escolhido em'),
        ),
        migrations.AddField(
            model_name='telegramphoto',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do arquivo'),
        ),
        migrations.AddField(
            model_name='telegramphoto',
            name='purpose',
            field=models.CharField(blank=True, choices=[('training', 'Treinamento'), ('test', 'Teste')], db_index=True, help_text='Vazio enquanto o usuário não responde se a imagem é para treinar ou testar.', max_length=20, verbose_name='Uso no modelo'),
        ),
        migrations.AlterField(
            model_name='telegramphoto',
            name='image',
            field=models.ImageField(blank=True, height_field='height', max_length=500, storage=telegram_bot.storage.AIMediaStorage(), upload_to=telegram_bot.models.telegram_photo_directory_path, verbose_name='Imagem', width_field='width'),
        ),
    ]
