# Generated by Django 3.2.25 on 2026-09-29 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0005_telegramphoto_uso_no_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramphoto',
            options={'ordering': ['-received_at'], 'permissions': [('approve_telegramphoto', 'Pode aprovar imagens de treino do modelo de IA')], 'verbose_name': 'Imagem do Telegram', 'verbose_name_plural': 'Imagens do Telegram'},
        ),
        migrations.AddField(
            model_name='telegramphoto',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovada em'),
        ),
        migrations.AddField(
            model_name='telegramphoto',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_telegram_photos', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada por'),
        ),
    ]
