# Generated by Django 3.2.25 on 2026-10-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_disease_states'),
        ('telegram_bot', '0006_telegramphoto_aprovacao_treino'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramphoto',
            name='awaiting_description',
            field=models.BooleanField(db_index=True, default=False, help_text='Imagem de treino já gravada cuja descrição o bot ainda espera do usuário.', verbose_name='Aguardando descrição'),
        ),
        migrations.AddField(
            model_name='telegramphoto',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição do envio'),
        ),
        migrations.AddField(
            model_name='telegramphoto',
            name='description_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número no lote'),
        ),
        migrations.AddField(
            model_name='telegramphoto',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_photos', to='disease.disease', verbose_name='Doença'),
        ),
        migrations.AddField(
            model_name='telegramphoto',
            name='disease_state',
            field=models.CharField(blank=True, max_length=60, verbose_name='Estado'),
        ),
    ]
