# Generated by Django 3.2.25 on 2025-12-11 17:08

import disease.models.culture
import disease.models.photo_disease
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(help_text='Digite o nome da cultura', max_length=100, verbose_name='Nome da cultura')),
                ('icon', models.FileField(blank=True, null=True, upload_to=disease.models.culture.culture_icon_directory_path, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Cultura',
                'verbose_name_plural': 'Culturas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_disease', models.CharField(help_text='Insira o nome da doença', max_length=100, verbose_name='Nome da doença')),
                ('scientific_name_disease', models.CharField(help_text='Insira o nome científico da doença', max_length=200, verbose_name='Nome científico')),
                ('complementary_scientific_name_disease', models.CharField(blank=True, help_text='Insira o nome científico complementar, caso houver', max_length=60, null=True, verbose_name='Nome Científico Complementar')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Identificador')),
                ('symptoms_disease', models.TextField(help_text='Insira uma descrição sobre os sintomas da doença', verbose_name='Sintomas')),
                ('cycle_disease', models.TextField(blank=True, help_text='Descreva o ciclo da doença', verbose_name='Ciclo da doença')),
                ('management_disease', models.TextField(blank=True, help_text='Descreva as medidas para controle desta doença', verbose_name='Medidas de controle')),
                ('environmental_conditions_disease', models.TextField(blank=True, help_text='Insira as condições ambientais de desenvolvimento', verbose_name='Condições ambientais de desenvolvimento')),
                ('references_disease', models.TextField(blank=True, help_text='Insira as referências utilizadas', null=True, verbose_name='Referências')),
                ('created_at_disease', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at_disease', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('published_disease', models.BooleanField(null=True, verbose_name='Publicado')),
                ('culture_disease', models.ForeignKey(help_text='Insira a cultura de lavoura afetada', on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='disease.culture', verbose_name='Cultura')),
            ],
            options={
                'verbose_name': 'Doença',
                'verbose_name_plural': 'Doenças',
                'ordering': ['name_disease'],
                'permissions': [('contribute_with_disease', 'Pode contribuir com doenças')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('initials', models.CharField(max_length=2, null=True, verbose_name='Sigla')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='disease.region', verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='PhotoDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to=disease.models.photo_disease.disease_directory_path, verbose_name='Imagens')),
                ('small_image', models.ImageField(editable=False, max_length=500, null=True, upload_to=disease.models.photo_disease.small_disease_directory_path)),
                ('published', models.BooleanField(null=True, verbose_name='Publicado')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='disease.disease', verbose_name='Doença')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='occurrence_regions_disease',
            field=models.ManyToManyField(blank=True, help_text='Selecione as regiões de ocorrência desta doença', to='disease.Region', verbose_name='Regiões de Ocorrência'),
        ),
    ]
