# Generated by Django 5.2.5 on 2025-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='occurrence_regions_disease',
            field=models.ManyToManyField(blank=True, help_text='Selecione as regiões de ocorrência desta doença', to='disease.region', verbose_name='Regiões de Ocorrência'),
        ),
    ]
