# Generated by Django 3.2.25 on 2026-09-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photodisease',
            options={'permissions': [('approve_photodisease', 'Pode aprovar fotos de doenças')], 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
    ]
