# Generated by Django 5.2.5 on 2025-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_add_condition_text_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='condition_text_disease',
            field=models.TextField(blank=True, help_text='Insira as condições ambientais de desenvolvimento', verbose_name='Condições ambientais de desenvolvimento'),
        ),
    ]
