# Generated by Django 3.2.25 on 2026-09-02 20:59

import core.validators
import disease.models.photo_disease
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_hold_existing_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodisease',
            name='image',
            field=models.ImageField(help_text='Resolução mínima: 1920x1080 (Full HD).', max_length=500, upload_to=disease.models.photo_disease.disease_directory_path, validators=[core.validators.validate_min_resolution], verbose_name='Imagens'),
        ),
    ]
