# Generated by Django 3.2.25 on 2026-10-06 21:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0004_alter_photodisease_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='states',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, help_text='Separados por vírgula. Ex.: doente,saudável', size=None, verbose_name='Estados da doença'),
        ),
    ]
