# Generated by Django 3.2.7 on 2024-05-08 21:05

from django.db import migrations, models
import django.db.models.deletion
import herbarium.models.photo


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('initials', models.CharField(max_length=2, null=True, verbose_name='Sigla')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='herbarium.region', verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('scientific_name', models.CharField(max_length=200, verbose_name='Nome científico')),
                ('complementary_scientific_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome Científico Complementar')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Identificador')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('importance', models.TextField(null=True, verbose_name='Importância')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Criado em')),
                ('published', models.BooleanField(null=True, verbose_name='Publicado')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='herbarium.family', verbose_name='Família')),
                ('occurrence_regions', models.ManyToManyField(to='herbarium.Region', verbose_name='Regiões de Ocorrência')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['name'],
                'permissions': [('contribute_with_plants', 'Pode contribuir com plantas')],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=herbarium.models.photo.plant_directory_path, verbose_name='Imagens')),
                ('small_image', models.ImageField(editable=False, null=True, upload_to=herbarium.models.photo.small_plant_directory_path)),
                ('published', models.BooleanField(null=True, verbose_name='Publicado')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='herbarium.plant', verbose_name='Planta')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
