# Generated by Django 2.2.2 on 2019-06-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0002_auto_20190628_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name'], 'verbose_name': 'Planta', 'verbose_name_plural': 'Plantas'},
        ),
        migrations.AddField(
            model_name='plant',
            name='division',
            field=models.CharField(blank=True, max_length=100, verbose_name='Divisão'),
        ),
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.CharField(blank=True, max_length=100, verbose_name='Família'),
        ),
        migrations.AddField(
            model_name='plant',
            name='order',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Identificador'),
        ),
    ]
