# Generated by Django 3.2.25 on 2026-09-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0002_seed_regions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'permissions': [('approve_photo', 'Pode aprovar fotos de plantas')], 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
    ]
