# Generated by Django 3.2.25 on 2026-09-02 20:59

import core.validators
from django.db import migrations, models
import herbarium.models.photo


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0004_publish_existing_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Resolução mínima: 1920x1080 (Full HD).', upload_to=herbarium.models.photo.plant_directory_path, validators=[core.validators.validate_min_resolution], verbose_name='Imagens'),
        ),
    ]
