# Generated by Django 2.2.2 on 2019-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0015_auto_20190816_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='family',
            field=models.CharField(blank=True, choices=[('amaranthaceae', 'Amaranthaceae'), ('asteraceae', 'Asteraceae'), ('brassicaceae', 'Brassicaceae'), ('caryophyllaceae', 'Caryophyllaceae'), ('cyperaceae', 'Cyperaceae'), ('convolvulaceae', 'Convolvulaceae'), ('euphobiaceae', 'Euphobiaceae'), ('malvaceae', 'Malvaceae'), ('plantaginaceae', 'Plantaginaceae'), ('poaceae', 'Poaceae'), ('polygonaceae', 'Polygonaceae'), ('rubiaceae', 'Rubiaceae'), ('sapindaceae', 'Sapindaceae'), ('solanaceae', 'Solanaceae')], max_length=100, verbose_name='Família'),
        ),
    ]
