# Generated by Django 3.0.2 on 2020-09-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0022_auto_20200916_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='division',
        ),
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Identificador'),
        ),
        migrations.DeleteModel(
            name='Division',
        ),
    ]
