# Generated by Django 3.0.2 on 2020-10-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0028_auto_20201005_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='occorrence_regions',
            new_name='occurrence_regions',
        ),
    ]
