# Generated by Django 3.0.2 on 2020-10-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0029_auto_20201005_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='initials',
            field=models.CharField(max_length=2, null=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nome'),
        ),
    ]
