# Generated by Django 3.0.2 on 2020-11-02 15:23

from django.db import migrations, models
import herbarium.models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0030_auto_20201005_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='small_image',
            field=models.ImageField(null=True, upload_to=herbarium.models.small_plant_directory_path),
        ),
    ]
