# Generated by Django 3.0.2 on 2020-11-03 14:29

from django.db import migrations, models
import django.db.models.deletion
import herbarium.models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0031_photo_small_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=herbarium.models.plant_directory_path, verbose_name='Imagens'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='small_image',
            field=models.ImageField(editable=False, null=True, upload_to=herbarium.models.small_plant_directory_path),
        ),
        migrations.AlterField(
            model_name='plant',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='herbarium.Family', verbose_name='Família'),
        ),
    ]
