# Generated by Django 3.1.3 on 2020-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0032_auto_20201103_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='Identificador'),
        ),
    ]
