# Generated by Django 3.1.3 on 2020-12-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0035_plant_scientific_name_complementary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='scientific_name_complementary',
            new_name='complementary_scientific_name',
        ),
    ]
