# Generated by Django 3.1.3 on 2021-03-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0036_auto_20201215_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='published',
            field=models.BooleanField(null=True, verbose_name='Publicado'),
        ),
    ]
