# Generated by Django 3.1.3 on 2021-06-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0037_plant_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name'], 'permissions': [('contribute_with_plants', 'Pode contribuir com plantas')], 'verbose_name': 'Planta', 'verbose_name_plural': 'Plantas'},
        ),
    ]
