# Generated by Django 3.1.3 on 2021-06-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0038_auto_20210610_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='published',
            field=models.BooleanField(null=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='herbarium.plant', verbose_name='Planta'),
        ),
    ]
