# Generated by Django 3.2.7 on 2024-07-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-time'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
