# Generated by Django 3.2.7 on 2024-11-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='get_messages',
        ),
    ]
