# Generated by Django 3.2.7 on 2024-11-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
        ('accounts', '0002_remove_profile_get_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alerts_for_diseases',
            field=models.ManyToManyField(to='disease.Disease', verbose_name='alertas para doenças'),
        ),
    ]
