# Generated by Django 3.2.7 on 2024-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['time'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='typesensor',
            name='metric',
            field=models.CharField(choices=[('mm', 'Milímetros'), ('C', 'Graus ºC'), ('CS', 'Graus ºC Solo'), ('human', 'Sensor Humano'), ('bool', 'Booleano'), ('ur', 'Umidade Relativa %'), ('%', 'Umidade % (depreciado)'), ('wm2', 'Wm2'), ('K', 'Graus ºK'), ('m/s', 'm/s (depreciado)'), ('m_s', 'm/s'), ('mbar', 'Milibares'), ('v', 'Volts'), ('pct', 'Porcentagem')], max_length=10),
        ),
    ]
