# Generated by Django 3.2.7 on 2024-12-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_alerts_for_diseases'),
        ('whatsapp_messages', '0003_rename_user_messageconfirmation_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageconfirmation',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
