# Generated by Django 3.2.7 on 2024-07-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20240715_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='math_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alerts.mathmodel', verbose_name='Modelo matematico'),
        ),
    ]
