# Generated by Django 3.2.7 on 2024-08-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_auto_20240819_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='used_internally',
        ),
    ]
