# Generated by Django 3.2.7 on 2024-08-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_remove_sensor_used_internally'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='math_model',
        ),
        migrations.AddField(
            model_name='intermediaryrequirement',
            name='math_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alerts.mathmodel', verbose_name='Modelo matemático'),
        ),
    ]
