# Generated by Django 3.2.7 on 2024-08-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_auto_20240821_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Reading',
        ),
    ]
