# Generated by Django 3.2.7 on 2024-08-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0012_auto_20240828_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['time'], 'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
    ]
