# Generated by Django 3.2.7 on 2024-10-19 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0016_auto_20241018_1541'),
        ('alerts', '0016_merge_20241017_1812'),
    ]

    operations = [
    ]
