# Generated by Django 3.2.7 on 2024-11-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0017_merge_20241018_2134'),
        ('alerts', '0017_useralert'),
    ]

    operations = [
    ]
