# Generated by Django 3.2.7 on 2024-11-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0018_merge_0017_merge_20241018_2134_0017_useralert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesensor',
            name='metric',
            field=models.CharField(choices=[('mm', 'Milímetros'), ('C', 'Graus ºC'), ('CS', 'Graus ºC Solo'), ('human', 'Sensor Humano'), ('bool', 'Booleano'), ('ur', 'Umidade Relativa %'), ('%', 'Umidade % (depreciado)'), ('wm2', 'Wm2'), ('K', 'Graus ºK'), ('m/s', 'm/s (depreciado)'), ('m_s', 'm/s'), ('mbar', 'Milibares'), ('v', 'Volts'), ('pct', 'Porcentagem'), ('int', 'Inteiro')], max_length=10),
        ),
    ]
