# Generated by Django 3.2.7 on 2024-12-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0021_auto_20241202_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='relational',
            field=models.CharField(blank=True, choices=[('>', 'Maior que'), ('<', 'Menor que'), ('>=', 'Maior ou igual que'), ('<=', 'Menor ou igual que'), ('==', 'Igual que'), ('!=', 'Diferente que')], max_length=10, verbose_name='Operador relacional'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requires',
            field=models.ManyToManyField(blank=True, to='alerts.Requirement', verbose_name='Requisitos'),
        ),
    ]
